-- Батч документів (Document → таблиця-транзакція + ТЧ). Транслітеровані імена; підписи uk у COMMENT.
-- NLS_LANG=.AL32UTF8. Повторюваний. FK — окремою секцією після CREATE (цикли/порядок).

DROP TABLE IF EXISTS RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_UNICHTOZHENIEDEL CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_UVEDOMLENIEPOSMS CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_PEREDACHADELVARKHIV CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_OTSUTSTVIE_ZAMESTITELI CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_OTSUTSTVIE CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_ISKHODYASHCHEEPISMO CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_EZHEDNEVNYI_OTCHET CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_VKHODYASHCHEEPISMO CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_BRON_POVTORENIEPODNYAM CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_BRON_ISKLYUCHENIYAPOVTORENIYA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_BRON CASCADE CONSTRAINTS;

-- Document.Бронь — Бронь
CREATE TABLE RSD_BRON (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    DOC_NO VARCHAR2(11 CHAR),
    IS_POSTED BOOLEAN DEFAULT FALSE,
    AVTOR_ID NUMBER,
    VESDEN BOOLEAN,
    DATANACHALA TIMESTAMP,
    DATANACHALAPOVTORENIYA DATE,
    DATAOKONCHANIYA TIMESTAMP,
    DATAOKONCHANIYAPOVTORENIYA DATE,
    INTERVALPOVTORENIYA NUMBER(10),
    KOLICHESTVOPOVTOROV NUMBER(10),
    KOLICHESTVOCHELOVEK NUMBER(5),
    KOMMENTARIY CLOB,
    POVTORENIEPODNYAMMESYATSA NUMBER(10),
    POVTORENIEPOMESYATSAM NUMBER(10),
    POLZOVATEL_ID NUMBER,
    POMESHCHENIE_ID NUMBER,
    PRAVILOOKONCHANIYAPOVTORENIYA_ID NUMBER,
    PREDMET_ID NUMBER,
    SPOSOBSOZDANIYABRONI_ID NUMBER,
    TEKHNICHESKOEOBESPECHENIE CLOB,
    TIPZAPISI_ID NUMBER,
    UDALITPOMESHCHENIE_ID NUMBER,
    KHOZYAYSTVENNOEOBESPECHENIE CLOB,
    CHASTOTAPOVTORENIYA_ID NUMBER,
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_BRON_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_BRON_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_BRON IS 'Бронь';
COMMENT ON COLUMN RSD_BRON.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_BRON.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_BRON.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_BRON.DOC_NO IS 'Номер документа';
COMMENT ON COLUMN RSD_BRON.IS_POSTED IS 'Проведено';
COMMENT ON COLUMN RSD_BRON.AVTOR_ID IS 'Автор';
COMMENT ON COLUMN RSD_BRON.VESDEN IS 'Весь день';
COMMENT ON COLUMN RSD_BRON.DATANACHALA IS 'Початок';
COMMENT ON COLUMN RSD_BRON.DATANACHALAPOVTORENIYA IS 'Дата початку повторення';
COMMENT ON COLUMN RSD_BRON.DATAOKONCHANIYA IS 'Закінчення';
COMMENT ON COLUMN RSD_BRON.DATAOKONCHANIYAPOVTORENIYA IS 'Дата закінчення повторення';
COMMENT ON COLUMN RSD_BRON.INTERVALPOVTORENIYA IS 'Інтервал повторення';
COMMENT ON COLUMN RSD_BRON.KOLICHESTVOPOVTOROV IS 'Кількість повторів';
COMMENT ON COLUMN RSD_BRON.KOLICHESTVOCHELOVEK IS 'Кількість осіб';
COMMENT ON COLUMN RSD_BRON.KOMMENTARIY IS 'Коментар';
COMMENT ON COLUMN RSD_BRON.POVTORENIEPODNYAMMESYATSA IS 'Повторення по днях місяця';
COMMENT ON COLUMN RSD_BRON.POVTORENIEPOMESYATSAM IS 'Повторення по місяцях';
COMMENT ON COLUMN RSD_BRON.POLZOVATEL_ID IS 'Користувач';
COMMENT ON COLUMN RSD_BRON.POMESHCHENIE_ID IS 'Приміщення';
COMMENT ON COLUMN RSD_BRON.PRAVILOOKONCHANIYAPOVTORENIYA_ID IS 'Правило закінчення повторення';
COMMENT ON COLUMN RSD_BRON.PREDMET_ID IS 'Предмет';
COMMENT ON COLUMN RSD_BRON.SPOSOBSOZDANIYABRONI_ID IS 'Спосіб створення броні';
COMMENT ON COLUMN RSD_BRON.TEKHNICHESKOEOBESPECHENIE IS 'Технічне забезпечення';
COMMENT ON COLUMN RSD_BRON.TIPZAPISI_ID IS 'Тип запису';
COMMENT ON COLUMN RSD_BRON.UDALITPOMESHCHENIE_ID IS 'Вилучити приміщення';
COMMENT ON COLUMN RSD_BRON.KHOZYAYSTVENNOEOBESPECHENIE IS 'Господарське забезпечення';
COMMENT ON COLUMN RSD_BRON.CHASTOTAPOVTORENIYA_ID IS 'Частота повторення';
COMMENT ON COLUMN RSD_BRON.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_BRON.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_BRON.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_BRON.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_BRON.UPDATED_BY IS 'Аудит: змінив';

-- ТЧ — Виключення повторення (ТЧ)
CREATE TABLE RSD_BRON_ISKLYUCHENIYAPOVTORENIYA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    DATAISKLYUCHENIYA DATE,
    ZAPISISKLYUCHENIYA_ID NUMBER,
    CONSTRAINT RSD_BRON_ISKLYUCHENIYAPOVTORENIYA_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_BRON_ISKLYUCHENIYAPOVTORENIYA IS 'Виключення повторення (ТЧ)';
COMMENT ON COLUMN RSD_BRON_ISKLYUCHENIYAPOVTORENIYA.ID IS 'Ключ';
COMMENT ON COLUMN RSD_BRON_ISKLYUCHENIYAPOVTORENIYA.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_BRON_ISKLYUCHENIYAPOVTORENIYA.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_BRON_ISKLYUCHENIYAPOVTORENIYA.DATAISKLYUCHENIYA IS 'Дата виключення';
COMMENT ON COLUMN RSD_BRON_ISKLYUCHENIYAPOVTORENIYA.ZAPISISKLYUCHENIYA_ID IS 'Запис виключення';

-- ТЧ — Повторення по днях (ТЧ)
CREATE TABLE RSD_BRON_POVTORENIEPODNYAM (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    DENNEDELI NUMBER(1),
    NOMERVKHOZHDENIYA NUMBER(3),
    CONSTRAINT RSD_BRON_POVTORENIEPODNYAM_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_BRON_POVTORENIEPODNYAM IS 'Повторення по днях (ТЧ)';
COMMENT ON COLUMN RSD_BRON_POVTORENIEPODNYAM.ID IS 'Ключ';
COMMENT ON COLUMN RSD_BRON_POVTORENIEPODNYAM.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_BRON_POVTORENIEPODNYAM.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_BRON_POVTORENIEPODNYAM.DENNEDELI IS 'День тижня';
COMMENT ON COLUMN RSD_BRON_POVTORENIEPODNYAM.NOMERVKHOZHDENIYA IS 'Номер входження';

-- Document.ВходящееПисьмо — Вхідний лист
CREATE TABLE RSD_VKHODYASHCHEEPISMO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    DOC_NO VARCHAR2(50 CHAR),
    VAZHNOST_ID NUMBER,
    VIDMARSHRUTIZATSII_ID NUMBER,
    VNUTRENNIYZAGOLOVOK CLOB,
    DATAOTPRAVKI TIMESTAMP,
    DATAPOLUCHENIYA TIMESTAMP,
    ESTVLOZHENIYA BOOLEAN,
    IDENTIFIKATORSOOBSHCHENIYA VARCHAR2(200 CHAR),
    KODIROVKA VARCHAR2(25 CHAR),
    KOMMENTARIY CLOB,
    NOMERSPOSOBAADRESATSII NUMBER(1),
    OTPRAVITELADRESAT_ID NUMBER,
    PAPKA_ID NUMBER,
    PREDMET_REF_TYPE VARCHAR2(60 CHAR),
    PREDMET_REF_ID NUMBER,
    PROEKT_ID NUMBER,
    RAZMER NUMBER(10),
    TEKSTPISMAHTMLKHRANILISHCHE BLOB,
    TEKSTPISMAPROSTOYTEKSTKHRANILISHCHE BLOB,
    TEKSTPISMARAZMECHENNYYTEKSTKHRANILISHCHE BLOB,
    TEMA VARCHAR2(1024 CHAR),
    TIPTEKSTA_ID NUMBER,
    UVEDOMITODOSTAVKE BOOLEAN,
    UVEDOMITOPROCHTENII BOOLEAN,
    UCHETNAYAZAPIS_ID NUMBER,
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_VKHODYASHCHEEPISMO_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_VKHODYASHCHEEPISMO_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_VKHODYASHCHEEPISMO IS 'Вхідний лист';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.DOC_NO IS 'Номер документа';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.VAZHNOST_ID IS 'Важливість';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.VIDMARSHRUTIZATSII_ID IS 'Вид маршрутизації';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.VNUTRENNIYZAGOLOVOK IS 'Внутрішній заголовок';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.DATAOTPRAVKI IS 'Дата відправлення';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.DATAPOLUCHENIYA IS 'Отримане';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.ESTVLOZHENIYA IS 'Є вкладення';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.IDENTIFIKATORSOOBSHCHENIYA IS 'Ідентифікатор повідомлення';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.KODIROVKA IS 'Кодування';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.KOMMENTARIY IS 'Коментар';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.NOMERSPOSOBAADRESATSII IS 'Номер способу адресації';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.OTPRAVITELADRESAT_ID IS 'Відправник адресат';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.PAPKA_ID IS 'Папка';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.PREDMET_REF_TYPE IS 'Предмет';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.PREDMET_REF_ID IS 'Предмет';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.PROEKT_ID IS 'Проект';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.RAZMER IS 'Розмір';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.TEKSTPISMAHTMLKHRANILISHCHE IS 'Текст листа (HTML)';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.TEKSTPISMAPROSTOYTEKSTKHRANILISHCHE IS 'Текст листа (простий текст)';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.TEKSTPISMARAZMECHENNYYTEKSTKHRANILISHCHE IS 'Текст листа (розмічений текст)';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.TEMA IS 'Тема';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.TIPTEKSTA_ID IS 'Тип тексту';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.UVEDOMITODOSTAVKE IS 'Повідомити про доставку';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.UVEDOMITOPROCHTENII IS 'Повідомити про прочитання';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.UCHETNAYAZAPIS_ID IS 'Обліковий запис';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO.UPDATED_BY IS 'Аудит: змінив';

-- ТЧ — Адреси повідомлення про прочитання (ТЧ)
CREATE TABLE RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ADRESAT_ID NUMBER,
    UDALITADRES VARCHAR2(100 CHAR),
    UDALITKONTAKT_REF_TYPE VARCHAR2(60 CHAR),
    UDALITKONTAKT_REF_ID NUMBER,
    UDALITOTOBRAZHAEMOEIMYA VARCHAR2(100 CHAR),
    CONSTRAINT RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII IS 'Адреси повідомлення про прочитання (ТЧ)';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII.ID IS 'Ключ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII.ADRESAT_ID IS 'Адресат';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII.UDALITADRES IS 'Вилучити адресу';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII.UDALITKONTAKT_REF_TYPE IS 'Вилучити контакт';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII.UDALITKONTAKT_REF_ID IS 'Вилучити контакт';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII.UDALITOTOBRAZHAEMOEIMYA IS 'Вилучити відображуване ім''я';

-- ТЧ — Додаткові реквізити (ТЧ)
CREATE TABLE RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    SVOYSTVO_ID NUMBER,
    TEKSTOVAYASTROKA CLOB,
    CONSTRAINT RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY IS 'Додаткові реквізити (ТЧ)';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.SVOYSTVO_ID IS 'Властивість';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.TEKSTOVAYASTROKA IS 'Текстовий рядок';

-- ТЧ — Одержувачі копій (ТЧ)
CREATE TABLE RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ADRESAT_ID NUMBER,
    CONSTRAINT RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY IS 'Одержувачі копій (ТЧ)';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY.ADRESAT_ID IS 'Адресат';

-- ТЧ — Одержувачі відповіді (ТЧ)
CREATE TABLE RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ADRESAT_ID NUMBER,
    CONSTRAINT RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA IS 'Одержувачі відповіді (ТЧ)';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA.ID IS 'Ключ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA.ADRESAT_ID IS 'Адресат';

-- ТЧ — Одержувачі листа (ТЧ)
CREATE TABLE RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ADRESAT_ID NUMBER,
    CONSTRAINT RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA IS 'Одержувачі листа (ТЧ)';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA.ID IS 'Ключ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA.ADRESAT_ID IS 'Адресат';

-- Document.ЕжедневныйОтчет — Щоденний звіт
CREATE TABLE RSD_EZHEDNEVNYI_OTCHET (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    DOC_NO VARCHAR2(9 CHAR),
    IS_POSTED BOOLEAN DEFAULT FALSE,
    AVTOR_ID NUMBER,
    DLITELNOSTRABOT VARCHAR2(5 CHAR),
    NACHALODNYA TIMESTAMP,
    NEKORREKTNAYADLITELNOST BOOLEAN,
    OKONCHANIEDNYA TIMESTAMP,
    PODRAZDELENIE_ID NUMBER,
    POLZOVATEL_ID NUMBER,
    SPOSOBUKAZANIYAVREMENI_ID NUMBER,
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_EZHEDNEVNYI_OTCHET IS 'Щоденний звіт';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.DOC_NO IS 'Номер документа';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.IS_POSTED IS 'Проведено';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.AVTOR_ID IS 'Автор';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.DLITELNOSTRABOT IS 'Тривалість робіт';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.NACHALODNYA IS 'Початок дня';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.NEKORREKTNAYADLITELNOST IS 'Некоректна тривалість';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.OKONCHANIEDNYA IS 'Закінчення дня';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.PODRAZDELENIE_ID IS 'Підрозділ';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.POLZOVATEL_ID IS 'Користувач';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.SPOSOBUKAZANIYAVREMENI_ID IS 'Спосіб зазначення часу';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET.UPDATED_BY IS 'Аудит: змінив';

-- ТЧ — Вилучити роботи (ТЧ)
CREATE TABLE RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    VIDRABOT_ID NUMBER,
    DATADOBAVLENIYA TIMESTAMP,
    DLITELNOST NUMBER(15),
    ISTOCHNIK_REF_TYPE VARCHAR2(60 CHAR),
    ISTOCHNIK_REF_ID NUMBER,
    NACHALO TIMESTAMP,
    OKONCHANIE TIMESTAMP,
    PROEKT_ID NUMBER,
    PROEKTNAYAZADACHA_ID NUMBER,
    RABOTA CLOB,
    SOZDANAAVTOMATICHESKI BOOLEAN,
    CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY IS 'Вилучити роботи (ТЧ)';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.VIDRABOT_ID IS 'Вид робіт';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.DATADOBAVLENIYA IS 'Дата додавання';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.DLITELNOST IS 'Тривалість';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.ISTOCHNIK_REF_TYPE IS 'Джерело';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.ISTOCHNIK_REF_ID IS 'Джерело';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.NACHALO IS 'Час початку роботи';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.OKONCHANIE IS 'Час закінчення роботи';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.PROEKT_ID IS 'Проект';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.PROEKTNAYAZADACHA_ID IS 'Проектна задача';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.RABOTA IS 'Зміст робіт';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY.SOZDANAAVTOMATICHESKI IS 'Створено автоматично';

-- ТЧ — Додаткові реквізити (ТЧ)
CREATE TABLE RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    SVOYSTVO_ID NUMBER,
    TEKSTOVAYASTROKA CLOB,
    CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY IS 'Додаткові реквізити (ТЧ)';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY.SVOYSTVO_ID IS 'Властивість';
COMMENT ON COLUMN RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY.TEKSTOVAYASTROKA IS 'Текстовий рядок';

-- Document.ИсходящееПисьмо — Вихідний лист
CREATE TABLE RSD_ISKHODYASHCHEEPISMO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    DOC_NO VARCHAR2(50 CHAR),
    AVTOR_ID NUMBER,
    VAZHNOST_ID NUMBER,
    VIDMARSHRUTIZATSII_ID NUMBER,
    DATAOTPRAVKI TIMESTAMP,
    ESTVLOZHENIYA BOOLEAN,
    IDENTIFIKATORSOOBSHCHENIYA VARCHAR2(200 CHAR),
    KODIROVKA VARCHAR2(25 CHAR),
    KOMMENTARIY CLOB,
    NOMERSPOSOBAADRESATSII NUMBER(1),
    OTPRAVITELKONTAKT_REF_TYPE VARCHAR2(60 CHAR),
    OTPRAVITELKONTAKT_REF_ID NUMBER,
    OTPRAVKAOTMENENA BOOLEAN,
    PAPKA_ID NUMBER,
    PISMOOSNOVANIE_REF_TYPE VARCHAR2(60 CHAR),
    PISMOOSNOVANIE_REF_ID NUMBER,
    PODGOTOVLENOKOTPRAVKE TIMESTAMP,
    POLUCHATELIPISMASTROKOY VARCHAR2(1024 CHAR),
    PREDMET_REF_TYPE VARCHAR2(60 CHAR),
    PREDMET_REF_ID NUMBER,
    PRICHINAVIDAMARSHRUTIZATSII CLOB,
    PROEKT_ID NUMBER,
    RAZMER NUMBER(10),
    TEKSTPISMAHTMLKHRANILISHCHE BLOB,
    TEKSTKHRANILISHCHE BLOB,
    TEMA VARCHAR2(1024 CHAR),
    TIPOTVETA_ID NUMBER,
    TIPTEKSTA_ID NUMBER,
    UVEDOMITODOSTAVKE BOOLEAN,
    UVEDOMITOPROCHTENII BOOLEAN,
    UCHETNAYAZAPIS_ID NUMBER,
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_ISKHODYASHCHEEPISMO_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_ISKHODYASHCHEEPISMO_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_ISKHODYASHCHEEPISMO IS 'Вихідний лист';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.DOC_NO IS 'Номер документа';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.AVTOR_ID IS 'Автор';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.VAZHNOST_ID IS 'Важливість';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.VIDMARSHRUTIZATSII_ID IS 'Вид маршрутизації';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.DATAOTPRAVKI IS 'Відправлене';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.ESTVLOZHENIYA IS 'Є вкладення';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.IDENTIFIKATORSOOBSHCHENIYA IS 'Ідентифікатор повідомлення';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.KODIROVKA IS 'Кодування';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.KOMMENTARIY IS 'Коментар';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.NOMERSPOSOBAADRESATSII IS 'Номер способу адресації';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.OTPRAVITELKONTAKT_REF_TYPE IS 'Відправник контакт';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.OTPRAVITELKONTAKT_REF_ID IS 'Відправник контакт';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.OTPRAVKAOTMENENA IS 'Відправлення скасоване';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.PAPKA_ID IS 'Папка';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.PISMOOSNOVANIE_REF_TYPE IS 'Лист підстава';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.PISMOOSNOVANIE_REF_ID IS 'Лист підстава';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.PODGOTOVLENOKOTPRAVKE IS 'Підготовлено до відправлення';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.POLUCHATELIPISMASTROKOY IS 'Кому';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.PREDMET_REF_TYPE IS 'Предмет';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.PREDMET_REF_ID IS 'Предмет';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.PRICHINAVIDAMARSHRUTIZATSII IS 'Причина виду маршрутизації';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.PROEKT_ID IS 'Проект';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.RAZMER IS 'Розмір';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.TEKSTPISMAHTMLKHRANILISHCHE IS 'Текст листа';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.TEKSTKHRANILISHCHE IS 'Текст листа';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.TEMA IS 'Тема';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.TIPOTVETA_ID IS 'Тип відповіді';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.TIPTEKSTA_ID IS 'Тип тексту';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.UVEDOMITODOSTAVKE IS 'Повідомити про доставку';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.UVEDOMITOPROCHTENII IS 'Повідомити про прочитання';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.UCHETNAYAZAPIS_ID IS 'Обліковий запис';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO.UPDATED_BY IS 'Аудит: змінив';

-- ТЧ — Додаткові реквізити (ТЧ)
CREATE TABLE RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    SVOYSTVO_ID NUMBER,
    TEKSTOVAYASTROKA CLOB,
    CONSTRAINT RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY IS 'Додаткові реквізити (ТЧ)';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.SVOYSTVO_ID IS 'Властивість';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY.TEKSTOVAYASTROKA IS 'Текстовий рядок';

-- ТЧ — Одержувачі копій (ТЧ)
CREATE TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ADRESAT_ID NUMBER,
    PORYADKOVYYNOMER NUMBER(10),
    CONSTRAINT RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY IS 'Одержувачі копій (ТЧ)';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY.ADRESAT_ID IS 'Адресат';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY.PORYADKOVYYNOMER IS 'Порядковий номер';

-- ТЧ — Одержувачі відповіді (ТЧ)
CREATE TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ADRESAT_ID NUMBER,
    PORYADKOVYYNOMER NUMBER(10),
    CONSTRAINT RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA IS 'Одержувачі відповіді (ТЧ)';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA.ID IS 'Ключ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA.ADRESAT_ID IS 'Адресат';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA.PORYADKOVYYNOMER IS 'Порядковий номер';

-- ТЧ — Одержувачі листа (ТЧ)
CREATE TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ADRESAT_ID NUMBER,
    PORYADKOVYYNOMER NUMBER(10),
    CONSTRAINT RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA IS 'Одержувачі листа (ТЧ)';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA.ID IS 'Ключ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA.ADRESAT_ID IS 'Адресат';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA.PORYADKOVYYNOMER IS 'Порядковий номер';

-- ТЧ — Одержувачі схованих копій (ТЧ)
CREATE TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ADRESAT_ID NUMBER,
    UDALITADRES VARCHAR2(100 CHAR),
    UDALITKONTAKT_REF_TYPE VARCHAR2(60 CHAR),
    UDALITKONTAKT_REF_ID NUMBER,
    UDALITOTOBRAZHAEMOEIMYA VARCHAR2(100 CHAR),
    PORYADKOVYYNOMER NUMBER(10),
    CONSTRAINT RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY IS 'Одержувачі схованих копій (ТЧ)';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY.ADRESAT_ID IS 'Адресат';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY.UDALITADRES IS 'Вилучити адресу';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY.UDALITKONTAKT_REF_TYPE IS 'Вилучити контакт';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY.UDALITKONTAKT_REF_ID IS 'Вилучити контакт';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY.UDALITOTOBRAZHAEMOEIMYA IS 'Вилучити відображуване ім''я';
COMMENT ON COLUMN RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY.PORYADKOVYYNOMER IS 'Порядковий номер';

-- Document.Отсутствие — Відсутність
CREATE TABLE RSD_OTSUTSTVIE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    DOC_NO VARCHAR2(11 CHAR),
    IS_POSTED BOOLEAN DEFAULT FALSE,
    AVTOR_ID NUMBER,
    BUDURAZBIRATZADACHI BOOLEAN,
    VESDEN BOOLEAN,
    VIDOTSUTSTVIYA_ID NUMBER,
    DATANACHALA TIMESTAMP,
    DATAOKONCHANIYA TIMESTAMP,
    KOMMENTARIY CLOB,
    PERIODSTROKOY VARCHAR2(100 CHAR),
    SOTRUDNIK_ID NUMBER,
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_OTSUTSTVIE_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_OTSUTSTVIE_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_OTSUTSTVIE IS 'Відсутність';
COMMENT ON COLUMN RSD_OTSUTSTVIE.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_OTSUTSTVIE.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_OTSUTSTVIE.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_OTSUTSTVIE.DOC_NO IS 'Номер документа';
COMMENT ON COLUMN RSD_OTSUTSTVIE.IS_POSTED IS 'Проведено';
COMMENT ON COLUMN RSD_OTSUTSTVIE.AVTOR_ID IS 'Автор';
COMMENT ON COLUMN RSD_OTSUTSTVIE.BUDURAZBIRATZADACHI IS 'Буду розбирати задачі';
COMMENT ON COLUMN RSD_OTSUTSTVIE.VESDEN IS 'Повний день';
COMMENT ON COLUMN RSD_OTSUTSTVIE.VIDOTSUTSTVIYA_ID IS 'Причина';
COMMENT ON COLUMN RSD_OTSUTSTVIE.DATANACHALA IS 'Початок';
COMMENT ON COLUMN RSD_OTSUTSTVIE.DATAOKONCHANIYA IS 'Закінчення';
COMMENT ON COLUMN RSD_OTSUTSTVIE.KOMMENTARIY IS 'Коментар';
COMMENT ON COLUMN RSD_OTSUTSTVIE.PERIODSTROKOY IS 'Період рядком';
COMMENT ON COLUMN RSD_OTSUTSTVIE.SOTRUDNIK_ID IS 'Хто';
COMMENT ON COLUMN RSD_OTSUTSTVIE.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_OTSUTSTVIE.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_OTSUTSTVIE.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_OTSUTSTVIE.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_OTSUTSTVIE.UPDATED_BY IS 'Аудит: змінив';

-- ТЧ — Заступники (ТЧ)
CREATE TABLE RSD_OTSUTSTVIE_ZAMESTITELI (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ZAMESTITEL_ID NUMBER,
    KOMMENTARIY CLOB,
    CONSTRAINT RSD_OTSUTSTVIE_ZAMESTITELI_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_OTSUTSTVIE_ZAMESTITELI IS 'Заступники (ТЧ)';
COMMENT ON COLUMN RSD_OTSUTSTVIE_ZAMESTITELI.ID IS 'Ключ';
COMMENT ON COLUMN RSD_OTSUTSTVIE_ZAMESTITELI.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_OTSUTSTVIE_ZAMESTITELI.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_OTSUTSTVIE_ZAMESTITELI.ZAMESTITEL_ID IS 'Заступник';
COMMENT ON COLUMN RSD_OTSUTSTVIE_ZAMESTITELI.KOMMENTARIY IS 'Коментар';

-- Document.ПередачаДелВАрхив — Передача справ в архів
CREATE TABLE RSD_PEREDACHADELVARKHIV (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    DOC_NO VARCHAR2(11 CHAR),
    KOMMENTARIY CLOB,
    ORGANIZATSIYA_ID NUMBER,
    OTVETSTVENNYY_ID NUMBER,
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_PEREDACHADELVARKHIV_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_PEREDACHADELVARKHIV_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_PEREDACHADELVARKHIV IS 'Передача справ в архів';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.DOC_NO IS 'Номер документа';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.KOMMENTARIY IS 'Коментар';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.ORGANIZATSIYA_ID IS 'Організація';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.OTVETSTVENNYY_ID IS 'Відповідальний';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV.UPDATED_BY IS 'Аудит: змінив';

-- ТЧ — Справи зберігання документів (ТЧ)
CREATE TABLE RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    DELOKHRANENIYADOKUMENTOV_ID NUMBER,
    CONSTRAINT RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV IS 'Справи зберігання документів (ТЧ)';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV.ID IS 'Ключ';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV.DELOKHRANENIYADOKUMENTOV_ID IS 'Справа зберігання документів';

-- Document.УведомлениеПоSMS — Оповіщення по SMS
CREATE TABLE RSD_UVEDOMLENIEPOSMS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    DOC_NO VARCHAR2(11 CHAR),
    IS_POSTED BOOLEAN DEFAULT FALSE,
    IDENTIFIKATOR VARCHAR2(100 CHAR),
    POLZOVATEL_ID NUMBER,
    STATUS_ID NUMBER,
    TEKST CLOB,
    TELEFON VARCHAR2(12 CHAR),
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_UVEDOMLENIEPOSMS_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_UVEDOMLENIEPOSMS_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_UVEDOMLENIEPOSMS IS 'Оповіщення по SMS';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.DOC_NO IS 'Номер документа';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.IS_POSTED IS 'Проведено';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.IDENTIFIKATOR IS 'Ідентифікатор';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.POLZOVATEL_ID IS 'Користувач';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.STATUS_ID IS 'Статус';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.TEKST IS 'Текст';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.TELEFON IS 'Телефон';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_UVEDOMLENIEPOSMS.UPDATED_BY IS 'Аудит: змінив';

-- Document.УничтожениеДел — Знищення справ
CREATE TABLE RSD_UNICHTOZHENIEDEL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    DOC_NO VARCHAR2(11 CHAR),
    KOMMENTARIY CLOB,
    ORGANIZATSIYA_ID NUMBER,
    OSNOVANIE CLOB,
    OTVETSTVENNYY_ID NUMBER,
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_UNICHTOZHENIEDEL_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_UNICHTOZHENIEDEL_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_UNICHTOZHENIEDEL IS 'Знищення справ';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.DOC_NO IS 'Номер документа';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.KOMMENTARIY IS 'Коментар';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.ORGANIZATSIYA_ID IS 'Організація';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.OSNOVANIE IS 'Підстава';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.OTVETSTVENNYY_ID IS 'Відповідальний';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL.UPDATED_BY IS 'Аудит: змінив';

-- ТЧ — Справи зберігання документів (ТЧ)
CREATE TABLE RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    DELOKHRANENIYADOKUMENTOV_ID NUMBER,
    CONSTRAINT RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV IS 'Справи зберігання документів (ТЧ)';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV.ID IS 'Ключ';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV.DELOKHRANENIYADOKUMENTOV_ID IS 'Справа зберігання документів';

-- ===== Зовнішні ключі (усі таблиці вже створені) =====
ALTER TABLE RSD_BRON ADD CONSTRAINT RSD_BRON_FK_AVTOR_ID FOREIGN KEY (AVTOR_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_BRON ADD CONSTRAINT RSD_BRON_FK_POLZOVATEL_ID FOREIGN KEY (POLZOVATEL_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_BRON ADD CONSTRAINT RSD_BRON_FK_POMESHCHENIE_ID FOREIGN KEY (POMESHCHENIE_ID) REFERENCES RSD_TERRITORIIIPOMESHCHENIYA (ID);
ALTER TABLE RSD_BRON ADD CONSTRAINT RSD_BRON_FK_PRAVILOOKONCHANIYAPOVTORENIYA_ID FOREIGN KEY (PRAVILOOKONCHANIYAPOVTORENIYA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_BRON ADD CONSTRAINT RSD_BRON_FK_SPOSOBSOZDANIYABRONI_ID FOREIGN KEY (SPOSOBSOZDANIYABRONI_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_BRON ADD CONSTRAINT RSD_BRON_FK_TIPZAPISI_ID FOREIGN KEY (TIPZAPISI_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_BRON ADD CONSTRAINT RSD_BRON_FK_UDALITPOMESHCHENIE_ID FOREIGN KEY (UDALITPOMESHCHENIE_ID) REFERENCES RSD_UDALITPOMESHCHENIYA (ID);
ALTER TABLE RSD_BRON ADD CONSTRAINT RSD_BRON_FK_CHASTOTAPOVTORENIYA_ID FOREIGN KEY (CHASTOTAPOVTORENIYA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_BRON_ISKLYUCHENIYAPOVTORENIYA ADD CONSTRAINT RSD_BRON_ISKLYUCHENIYAPOVTORENIYA_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_BRON (ID);
ALTER TABLE RSD_BRON_POVTORENIEPODNYAM ADD CONSTRAINT RSD_BRON_POVTORENIEPODNYAM_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_BRON (ID);
ALTER TABLE RSD_VKHODYASHCHEEPISMO ADD CONSTRAINT RSD_VKHODYASHCHEEPISMO_FK_VAZHNOST_ID FOREIGN KEY (VAZHNOST_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_VKHODYASHCHEEPISMO ADD CONSTRAINT RSD_VKHODYASHCHEEPISMO_FK_VIDMARSHRUTIZATSII_ID FOREIGN KEY (VIDMARSHRUTIZATSII_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_VKHODYASHCHEEPISMO ADD CONSTRAINT RSD_VKHODYASHCHEEPISMO_FK_PAPKA_ID FOREIGN KEY (PAPKA_ID) REFERENCES RSD_PAPKIPISEM (ID);
ALTER TABLE RSD_VKHODYASHCHEEPISMO ADD CONSTRAINT RSD_VKHODYASHCHEEPISMO_FK_TIPTEKSTA_ID FOREIGN KEY (TIPTEKSTA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII ADD CONSTRAINT RSD_VKHODYASHCHEEPISMO_ADRESAUVEDOMLENIYAOPROCHTENII_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_VKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY ADD CONSTRAINT RSD_VKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_VKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY ADD CONSTRAINT RSD_VKHODYASHCHEEPISMO_POLUCHATELIKOPIY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_VKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA ADD CONSTRAINT RSD_VKHODYASHCHEEPISMO_POLUCHATELIOTVETA_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_VKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA ADD CONSTRAINT RSD_VKHODYASHCHEEPISMO_POLUCHATELIPISMA_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_VKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_EZHEDNEVNYI_OTCHET ADD CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_FK_AVTOR_ID FOREIGN KEY (AVTOR_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_EZHEDNEVNYI_OTCHET ADD CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_FK_PODRAZDELENIE_ID FOREIGN KEY (PODRAZDELENIE_ID) REFERENCES RSD_STRUKTURAPREDPRIYATIYA (ID);
ALTER TABLE RSD_EZHEDNEVNYI_OTCHET ADD CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_FK_POLZOVATEL_ID FOREIGN KEY (POLZOVATEL_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_EZHEDNEVNYI_OTCHET ADD CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_FK_SPOSOBUKAZANIYAVREMENI_ID FOREIGN KEY (SPOSOBUKAZANIYAVREMENI_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY ADD CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY_FK_VIDRABOT_ID FOREIGN KEY (VIDRABOT_ID) REFERENCES RSD_VIDYRABOT (ID);
ALTER TABLE RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY ADD CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_UDALITRABOTY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_EZHEDNEVNYI_OTCHET (ID);
ALTER TABLE RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY ADD CONSTRAINT RSD_EZHEDNEVNYI_OTCHET_DOPOLNITELNYEREKVIZITY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_EZHEDNEVNYI_OTCHET (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_FK_AVTOR_ID FOREIGN KEY (AVTOR_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_FK_VAZHNOST_ID FOREIGN KEY (VAZHNOST_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_FK_VIDMARSHRUTIZATSII_ID FOREIGN KEY (VIDMARSHRUTIZATSII_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_FK_PAPKA_ID FOREIGN KEY (PAPKA_ID) REFERENCES RSD_PAPKIPISEM (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_FK_TIPOTVETA_ID FOREIGN KEY (TIPOTVETA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_FK_TIPTEKSTA_ID FOREIGN KEY (TIPTEKSTA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_DOPOLNITELNYEREKVIZITY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_ISKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_POLUCHATELIKOPIY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_ISKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_POLUCHATELIOTVETA_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_ISKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_POLUCHATELIPISMA_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_ISKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY ADD CONSTRAINT RSD_ISKHODYASHCHEEPISMO_POLUCHATELISKRYTYKHKOPIY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_ISKHODYASHCHEEPISMO (ID);
ALTER TABLE RSD_OTSUTSTVIE ADD CONSTRAINT RSD_OTSUTSTVIE_FK_AVTOR_ID FOREIGN KEY (AVTOR_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_OTSUTSTVIE ADD CONSTRAINT RSD_OTSUTSTVIE_FK_SOTRUDNIK_ID FOREIGN KEY (SOTRUDNIK_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_OTSUTSTVIE_ZAMESTITELI ADD CONSTRAINT RSD_OTSUTSTVIE_ZAMESTITELI_FK_ZAMESTITEL_ID FOREIGN KEY (ZAMESTITEL_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_OTSUTSTVIE_ZAMESTITELI ADD CONSTRAINT RSD_OTSUTSTVIE_ZAMESTITELI_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_OTSUTSTVIE (ID);
ALTER TABLE RSD_PEREDACHADELVARKHIV ADD CONSTRAINT RSD_PEREDACHADELVARKHIV_FK_ORGANIZATSIYA_ID FOREIGN KEY (ORGANIZATSIYA_ID) REFERENCES RSD_ORGANIZATIONS (ID);
ALTER TABLE RSD_PEREDACHADELVARKHIV ADD CONSTRAINT RSD_PEREDACHADELVARKHIV_FK_OTVETSTVENNYY_ID FOREIGN KEY (OTVETSTVENNYY_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV ADD CONSTRAINT RSD_PEREDACHADELVARKHIV_DELAKHRANENIYADOKUMENTOV_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_PEREDACHADELVARKHIV (ID);
ALTER TABLE RSD_UVEDOMLENIEPOSMS ADD CONSTRAINT RSD_UVEDOMLENIEPOSMS_FK_POLZOVATEL_ID FOREIGN KEY (POLZOVATEL_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_UVEDOMLENIEPOSMS ADD CONSTRAINT RSD_UVEDOMLENIEPOSMS_FK_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_UNICHTOZHENIEDEL ADD CONSTRAINT RSD_UNICHTOZHENIEDEL_FK_ORGANIZATSIYA_ID FOREIGN KEY (ORGANIZATSIYA_ID) REFERENCES RSD_ORGANIZATIONS (ID);
ALTER TABLE RSD_UNICHTOZHENIEDEL ADD CONSTRAINT RSD_UNICHTOZHENIEDEL_FK_OTVETSTVENNYY_ID FOREIGN KEY (OTVETSTVENNYY_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV ADD CONSTRAINT RSD_UNICHTOZHENIEDEL_DELAKHRANENIYADOKUMENTOV_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_UNICHTOZHENIEDEL (ID);
