-- Батч документів (Document → таблиця-транзакція + ТЧ). Транслітеровані імена; підписи uk у COMMENT.
-- NLS_LANG=.AL32UTF8. Повторюваний. FK — окремою секцією після CREATE (цикли/порядок).

DROP TABLE IF EXISTS RSD_ZADACHAISPOLNITELYA_PREDMETY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_ZADACHAISPOLNITELYA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_SOGLASOVANIE_PREDMETYZADACH CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_SOGLASOVANIE_PREDMETY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_SOGLASOVANIE_ISPOLNITELI CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS RSD_SOGLASOVANIE CASCADE CONSTRAINTS;

-- BusinessProcess.Согласование — Погодження
CREATE TABLE RSD_SOGLASOVANIE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    AVTOR_ID NUMBER,
    VAZHNOST_ID NUMBER,
    VARIANTSOGLASOVANIYA_ID NUMBER,
    VARIANTUSTANOVKISROKAOBRABOTKIREZULTATOV_ID NUMBER,
    GLAVNAYAZADACHA_ID NUMBER,
    DATAZAVERSHENIYA TIMESTAMP,
    DATANACHALA TIMESTAMP,
    KOLICHESTVOITERATSIY NUMBER(2),
    NAIMENOVANIE VARCHAR2(150 CHAR),
    NOMERITERATSII NUMBER(10),
    OPISANIE CLOB,
    POVTORITSOGLASOVANIE BOOLEAN,
    PODPISYVATEP BOOLEAN,
    PRICHINAPRERYVANIYA VARCHAR2(100 CHAR),
    PROEKT_ID NUMBER,
    PROEKTNAYAZADACHA_ID NUMBER,
    REZULTATSOGLASOVANIYA_ID NUMBER,
    SOSTOYANIE_ID NUMBER,
    SROKISPOLNENIYAPROTSESSA TIMESTAMP,
    SROKOBRABOTKIREZULTATOV TIMESTAMP,
    SROKOBRABOTKIREZULTATOVDNI NUMBER(3),
    SROKOBRABOTKIREZULTATOVMINUTY NUMBER(3),
    SROKOBRABOTKIREZULTATOVCHASY NUMBER(3),
    TRUDOZATRATYPLANAVTORA NUMBER(10,2),
    TRUDOZATRATYPLANISPOLNITELYA NUMBER(10,2),
    UDALITPREDMET_REF_TYPE VARCHAR2(60 CHAR),
    UDALITPREDMET_REF_ID NUMBER,
    UDALITRAZNYESROKI BOOLEAN,
    UDALITSROKISPOLNENIYA NUMBER(2),
    UDALITSROKISPOLNENIYADATOY TIMESTAMP,
    UDALITSROKISPOLNENIYACHAS NUMBER(2),
    UZELOBMENA VARCHAR2(36),
    SHABLON_ID NUMBER,
    ETAPOBRABOTKIPREDMETA VARCHAR2(100 CHAR),
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_SOGLASOVANIE_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_SOGLASOVANIE_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_SOGLASOVANIE IS 'Погодження';
COMMENT ON COLUMN RSD_SOGLASOVANIE.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_SOGLASOVANIE.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_SOGLASOVANIE.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_SOGLASOVANIE.AVTOR_ID IS 'Автор';
COMMENT ON COLUMN RSD_SOGLASOVANIE.VAZHNOST_ID IS 'Важливість';
COMMENT ON COLUMN RSD_SOGLASOVANIE.VARIANTSOGLASOVANIYA_ID IS 'Варіант погодження';
COMMENT ON COLUMN RSD_SOGLASOVANIE.VARIANTUSTANOVKISROKAOBRABOTKIREZULTATOV_ID IS 'Варіант встановлення строку обробки результатів';
COMMENT ON COLUMN RSD_SOGLASOVANIE.GLAVNAYAZADACHA_ID IS 'Головна задача';
COMMENT ON COLUMN RSD_SOGLASOVANIE.DATAZAVERSHENIYA IS 'Дата завершення';
COMMENT ON COLUMN RSD_SOGLASOVANIE.DATANACHALA IS 'Дата початку';
COMMENT ON COLUMN RSD_SOGLASOVANIE.KOLICHESTVOITERATSIY IS 'Кількість ітерацій';
COMMENT ON COLUMN RSD_SOGLASOVANIE.NAIMENOVANIE IS 'Найменування';
COMMENT ON COLUMN RSD_SOGLASOVANIE.NOMERITERATSII IS 'Номер поточної ітерації';
COMMENT ON COLUMN RSD_SOGLASOVANIE.OPISANIE IS 'Опис';
COMMENT ON COLUMN RSD_SOGLASOVANIE.POVTORITSOGLASOVANIE IS 'Повторити погодження';
COMMENT ON COLUMN RSD_SOGLASOVANIE.PODPISYVATEP IS 'Підписувати ЕП';
COMMENT ON COLUMN RSD_SOGLASOVANIE.PRICHINAPRERYVANIYA IS 'Причина переривання';
COMMENT ON COLUMN RSD_SOGLASOVANIE.PROEKT_ID IS 'Проект';
COMMENT ON COLUMN RSD_SOGLASOVANIE.PROEKTNAYAZADACHA_ID IS 'Проектна задача';
COMMENT ON COLUMN RSD_SOGLASOVANIE.REZULTATSOGLASOVANIYA_ID IS 'Результат погодження';
COMMENT ON COLUMN RSD_SOGLASOVANIE.SOSTOYANIE_ID IS 'Стан';
COMMENT ON COLUMN RSD_SOGLASOVANIE.SROKISPOLNENIYAPROTSESSA IS 'Строк виконання процесу';
COMMENT ON COLUMN RSD_SOGLASOVANIE.SROKOBRABOTKIREZULTATOV IS 'Строк обробки результатів';
COMMENT ON COLUMN RSD_SOGLASOVANIE.SROKOBRABOTKIREZULTATOVDNI IS 'Строк обробки результатів дні';
COMMENT ON COLUMN RSD_SOGLASOVANIE.SROKOBRABOTKIREZULTATOVMINUTY IS 'Строк обробки результатів хвилини';
COMMENT ON COLUMN RSD_SOGLASOVANIE.SROKOBRABOTKIREZULTATOVCHASY IS 'Строк обробки результатів години';
COMMENT ON COLUMN RSD_SOGLASOVANIE.TRUDOZATRATYPLANAVTORA IS 'Планові трудовитрати автора';
COMMENT ON COLUMN RSD_SOGLASOVANIE.TRUDOZATRATYPLANISPOLNITELYA IS 'Планові трудовитрати, що погодять';
COMMENT ON COLUMN RSD_SOGLASOVANIE.UDALITPREDMET_REF_TYPE IS 'Вилучити предмет';
COMMENT ON COLUMN RSD_SOGLASOVANIE.UDALITPREDMET_REF_ID IS 'Вилучити предмет';
COMMENT ON COLUMN RSD_SOGLASOVANIE.UDALITRAZNYESROKI IS 'Видалити різні строки';
COMMENT ON COLUMN RSD_SOGLASOVANIE.UDALITSROKISPOLNENIYA IS 'Строк погодження';
COMMENT ON COLUMN RSD_SOGLASOVANIE.UDALITSROKISPOLNENIYADATOY IS 'Видалити строк виконання датою';
COMMENT ON COLUMN RSD_SOGLASOVANIE.UDALITSROKISPOLNENIYACHAS IS 'Строк погодження';
COMMENT ON COLUMN RSD_SOGLASOVANIE.UZELOBMENA IS 'Вузол обміну';
COMMENT ON COLUMN RSD_SOGLASOVANIE.SHABLON_ID IS 'Шаблон процесу';
COMMENT ON COLUMN RSD_SOGLASOVANIE.ETAPOBRABOTKIPREDMETA IS 'Етап обробки предмета';
COMMENT ON COLUMN RSD_SOGLASOVANIE.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_SOGLASOVANIE.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_SOGLASOVANIE.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_SOGLASOVANIE.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_SOGLASOVANIE.UPDATED_BY IS 'Аудит: змінив';

-- ТЧ — Додаткові реквізити (ТЧ)
CREATE TABLE RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    SVOYSTVO_ID NUMBER,
    TEKSTOVAYASTROKA CLOB,
    CONSTRAINT RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY IS 'Додаткові реквізити (ТЧ)';
COMMENT ON COLUMN RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY.SVOYSTVO_ID IS 'Властивість';
COMMENT ON COLUMN RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY.TEKSTOVAYASTROKA IS 'Текстовий рядок';

-- ТЧ — Аркуш погодження (ТЧ)
CREATE TABLE RSD_SOGLASOVANIE_ISPOLNITELI (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    VARIANTUSTANOVKISROKAISPOLNENIYA_ID NUMBER,
    ZADACHAISPOLNITELYA_ID NUMBER,
    UDALITISPOLNITEL_REF_TYPE VARCHAR2(60 CHAR),
    UDALITISPOLNITEL_REF_ID NUMBER,
    ISPOLNITEL_REF_TYPE VARCHAR2(60 CHAR),
    ISPOLNITEL_REF_ID NUMBER,
    PORYADOKSOGLASOVANIYA_ID NUMBER,
    PROYDEN BOOLEAN,
    SROKISPOLNENIYA TIMESTAMP,
    SROKISPOLNENIYADNI NUMBER(3),
    SROKISPOLNENIYAMINUTY NUMBER(3),
    SROKISPOLNENIYACHASY NUMBER(3),
    TRUDOZATRATYPLANISPOLNITELYA NUMBER(10,2),
    UDALITSROKISPOLNENIYA NUMBER(2),
    UDALITSROKISPOLNENIYACHAS NUMBER(2),
    CONSTRAINT RSD_SOGLASOVANIE_ISPOLNITELI_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_SOGLASOVANIE_ISPOLNITELI IS 'Аркуш погодження (ТЧ)';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.ID IS 'Ключ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.VARIANTUSTANOVKISROKAISPOLNENIYA_ID IS 'Варіант встановлення строку виконання';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.ZADACHAISPOLNITELYA_ID IS 'Задача виконавця';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.UDALITISPOLNITEL_REF_TYPE IS '(не використовується) Виконавець';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.UDALITISPOLNITEL_REF_ID IS '(не використовується) Виконавець';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.ISPOLNITEL_REF_TYPE IS 'Виконавець';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.ISPOLNITEL_REF_ID IS 'Виконавець';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.PORYADOKSOGLASOVANIYA_ID IS 'Порядок погодження';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.PROYDEN IS 'Пройдений';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.SROKISPOLNENIYA IS 'Строк виконання';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.SROKISPOLNENIYADNI IS 'Строк виконання дні';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.SROKISPOLNENIYAMINUTY IS 'Строк виконання хвилини';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.SROKISPOLNENIYACHASY IS 'Строк виконання години';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.TRUDOZATRATYPLANISPOLNITELYA IS 'Планові трудовитрати, що погодять';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.UDALITSROKISPOLNENIYA IS 'Строк погодження';
COMMENT ON COLUMN RSD_SOGLASOVANIE_ISPOLNITELI.UDALITSROKISPOLNENIYACHAS IS 'Строк погодження';

-- ТЧ — Предмети (ТЧ)
CREATE TABLE RSD_SOGLASOVANIE_PREDMETY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ROLPREDMETA_ID NUMBER,
    IMYAPREDMETA_ID NUMBER,
    IMYAPREDMETAOSNOVANIE_ID NUMBER,
    PREDMET_REF_TYPE VARCHAR2(60 CHAR),
    PREDMET_REF_ID NUMBER,
    SHABLONOSNOVANIE_REF_TYPE VARCHAR2(60 CHAR),
    SHABLONOSNOVANIE_REF_ID NUMBER,
    CONSTRAINT RSD_SOGLASOVANIE_PREDMETY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_SOGLASOVANIE_PREDMETY IS 'Предмети (ТЧ)';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.ROLPREDMETA_ID IS 'Роль предмета';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.IMYAPREDMETA_ID IS 'Ім''я предмета';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.IMYAPREDMETAOSNOVANIE_ID IS 'Ім''я предмета підстава';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.PREDMET_REF_TYPE IS 'Предмет';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.PREDMET_REF_ID IS 'Предмет';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.SHABLONOSNOVANIE_REF_TYPE IS 'Шаблон підстава';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETY.SHABLONOSNOVANIE_REF_ID IS 'Шаблон підстава';

-- ТЧ — Предмети задач (ТЧ)
CREATE TABLE RSD_SOGLASOVANIE_PREDMETYZADACH (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    TOCHKAMARSHRUTA_ID NUMBER,
    IMYAPREDMETA_ID NUMBER,
    OBYAZATELNOEZAPOLNENIE BOOLEAN,
    DOSTUPNOUDALENIE BOOLEAN,
    CONSTRAINT RSD_SOGLASOVANIE_PREDMETYZADACH_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_SOGLASOVANIE_PREDMETYZADACH IS 'Предмети задач (ТЧ)';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETYZADACH.ID IS 'Ключ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETYZADACH.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETYZADACH.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETYZADACH.TOCHKAMARSHRUTA_ID IS 'Точка маршруту';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETYZADACH.IMYAPREDMETA_ID IS 'Ім''я предмета';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETYZADACH.OBYAZATELNOEZAPOLNENIE IS 'Обов''язкове заповнення';
COMMENT ON COLUMN RSD_SOGLASOVANIE_PREDMETYZADACH.DOSTUPNOUDALENIE IS 'Доступне вилучення';

-- ТЧ — Результати ознайомлень (ТЧ)
CREATE TABLE RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    NOMERITERATSII NUMBER(10),
    ZADACHAISPOLNITELYA_ID NUMBER,
    OTPRAVLENONAPOVTORNOESOGLASOVANIE BOOLEAN,
    CONSTRAINT RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY IS 'Результати ознайомлень (ТЧ)';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY.NOMERITERATSII IS 'Номер ітерації';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY.ZADACHAISPOLNITELYA_ID IS 'Задача виконавця';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY.OTPRAVLENONAPOVTORNOESOGLASOVANIE IS 'Відправлено на повторне погодження';

-- ТЧ — Результати погодження (ТЧ)
CREATE TABLE RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    NOMERITERATSII NUMBER(10),
    ZADACHAISPOLNITELYA_ID NUMBER,
    REZULTATSOGLASOVANIYA_ID NUMBER,
    CONSTRAINT RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA IS 'Результати погодження (ТЧ)';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA.ID IS 'Ключ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA.NOMERITERATSII IS 'Номер ітерації';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA.ZADACHAISPOLNITELYA_ID IS 'Задача виконавця';
COMMENT ON COLUMN RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA.REZULTATSOGLASOVANIYA_ID IS 'Результат погодження';

-- ТЧ — Вилучити додаткові виконавці (ТЧ)
CREATE TABLE RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ISPOLNITEL_REF_TYPE VARCHAR2(60 CHAR),
    ISPOLNITEL_REF_ID NUMBER,
    CONSTRAINT RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI IS 'Вилучити додаткові виконавці (ТЧ)';
COMMENT ON COLUMN RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI.ID IS 'Ключ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI.ISPOLNITEL_REF_TYPE IS 'Виконавець';
COMMENT ON COLUMN RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI.ISPOLNITEL_REF_ID IS 'Виконавець';

-- Task.ЗадачаИсполнителя — Задача
CREATE TABLE RSD_ZADACHAISPOLNITELYA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LEGACY_REF VARCHAR2(36) NOT NULL,
    DOC_DATE TIMESTAMP,
    AVTOR_ID NUMBER,
    VAZHNOST_ID NUMBER,
    DATAISPOLNENIYA TIMESTAMP,
    DATANACHALA TIMESTAMP,
    OPISANIE CLOB,
    DATAPRINYATIYAKISPOLNENIYU TIMESTAMP,
    ISKLYUCHENAIZPROTSESSA BOOLEAN,
    UDALITPREDMET_REF_TYPE VARCHAR2(60 CHAR),
    UDALITPREDMET_REF_ID NUMBER,
    OTMENENA BOOLEAN,
    PREDMETSTROKOY VARCHAR2(500 CHAR),
    PRINYATAKISPOLNENIYU BOOLEAN,
    PROEKT_ID NUMBER,
    PROEKTNAYAZADACHA_ID NUMBER,
    REZULTATVYPOLNENIYA CLOB,
    SOSTOYANIEBIZNESPROTSESSA_ID NUMBER,
    SROKISPOLNENIYA TIMESTAMP,
    UDALITTEKUSHCHIYISPOLNITEL_REF_TYPE VARCHAR2(60 CHAR),
    UDALITTEKUSHCHIYISPOLNITEL_REF_ID NUMBER,
    AVTORSTROKOY VARCHAR2(150 CHAR),
    TEKUSHCHIYISPOLNITEL_REF_TYPE VARCHAR2(60 CHAR),
    TEKUSHCHIYISPOLNITEL_REF_ID NUMBER,
    PRIZNAKPROVEDENIYATENDERA BOOLEAN,
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(255 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER) NOT NULL,
    CONSTRAINT RSD_ZADACHAISPOLNITELYA_PK PRIMARY KEY (ID),
    CONSTRAINT RSD_ZADACHAISPOLNITELYA_UK_LEGACY_REF_ UNIQUE (LEGACY_REF)
);
COMMENT ON TABLE RSD_ZADACHAISPOLNITELYA IS 'Задача';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.ID IS 'Сурогатний ключ';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.LEGACY_REF IS 'UUID 1С — звірка';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.DOC_DATE IS 'Дата документа';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.AVTOR_ID IS 'Автор';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.VAZHNOST_ID IS 'Важливість';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.DATAISPOLNENIYA IS 'Дата виконання';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.DATANACHALA IS 'Дата початку';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.OPISANIE IS 'Опис';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.DATAPRINYATIYAKISPOLNENIYU IS 'Дата прийняття до виконання';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.ISKLYUCHENAIZPROTSESSA IS 'Виключена із процесу';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.UDALITPREDMET_REF_TYPE IS 'Вилучити предмет';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.UDALITPREDMET_REF_ID IS 'Вилучити предмет';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.OTMENENA IS 'Скасовано';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.PREDMETSTROKOY IS 'Предмет';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.PRINYATAKISPOLNENIYU IS 'Прийнята до виконання';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.PROEKT_ID IS 'Проект';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.PROEKTNAYAZADACHA_ID IS 'Проектна задача';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.REZULTATVYPOLNENIYA IS 'Результат опрацювання';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.SOSTOYANIEBIZNESPROTSESSA_ID IS 'Стан бізнес процесу';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.SROKISPOLNENIYA IS 'Строк';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.UDALITTEKUSHCHIYISPOLNITEL_REF_TYPE IS '(не використовується) Поточний виконавець';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.UDALITTEKUSHCHIYISPOLNITEL_REF_ID IS '(не використовується) Поточний виконавець';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.AVTORSTROKOY IS 'Автор рядком';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.TEKUSHCHIYISPOLNITEL_REF_TYPE IS 'Поточний виконавець';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.TEKUSHCHIYISPOLNITEL_REF_ID IS 'Поточний виконавець';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.PRIZNAKPROVEDENIYATENDERA IS 'Ознака проведення тендера';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.IS_DELETED IS 'Мʼяке видалення';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.CREATED_AT IS 'Аудит: створено';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.CREATED_BY IS 'Аудит: створив';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.UPDATED_AT IS 'Аудит: змінено';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA.UPDATED_BY IS 'Аудит: змінив';

-- ТЧ — Додаткові реквізити (ТЧ)
CREATE TABLE RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    SVOYSTVO_ID NUMBER,
    TEKSTOVAYASTROKA CLOB,
    CONSTRAINT RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY IS 'Додаткові реквізити (ТЧ)';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY.SVOYSTVO_ID IS 'Властивість';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY.TEKSTOVAYASTROKA IS 'Текстовий рядок';

-- ТЧ — Предмети (ТЧ)
CREATE TABLE RSD_ZADACHAISPOLNITELYA_PREDMETY (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    OWNER_ID NUMBER NOT NULL,
    LINE_NO NUMBER NOT NULL,
    ROLPREDMETA_ID NUMBER,
    IMYAPREDMETA_ID NUMBER,
    PREDMET_REF_TYPE VARCHAR2(60 CHAR),
    PREDMET_REF_ID NUMBER,
    DOSTUPNOUDALENIE BOOLEAN,
    OBYAZATELNOEZAPOLNENIE BOOLEAN,
    CONSTRAINT RSD_ZADACHAISPOLNITELYA_PREDMETY_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE RSD_ZADACHAISPOLNITELYA_PREDMETY IS 'Предмети (ТЧ)';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_PREDMETY.ID IS 'Ключ';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_PREDMETY.OWNER_ID IS 'Власник ТЧ';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_PREDMETY.LINE_NO IS 'Номер рядка';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_PREDMETY.ROLPREDMETA_ID IS 'Роль предмета';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_PREDMETY.IMYAPREDMETA_ID IS 'Ім''я предмета';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_PREDMETY.PREDMET_REF_TYPE IS 'Предмет';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_PREDMETY.PREDMET_REF_ID IS 'Предмет';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_PREDMETY.DOSTUPNOUDALENIE IS 'Доступне вилучення';
COMMENT ON COLUMN RSD_ZADACHAISPOLNITELYA_PREDMETY.OBYAZATELNOEZAPOLNENIE IS 'Обов''язкове заповнення';

-- ===== Зовнішні ключі (усі таблиці вже створені) =====
ALTER TABLE RSD_SOGLASOVANIE ADD CONSTRAINT RSD_SOGLASOVANIE_FK_AVTOR_ID FOREIGN KEY (AVTOR_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_SOGLASOVANIE ADD CONSTRAINT RSD_SOGLASOVANIE_FK_VAZHNOST_ID FOREIGN KEY (VAZHNOST_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_SOGLASOVANIE ADD CONSTRAINT RSD_SOGLASOVANIE_FK_VARIANTSOGLASOVANIYA_ID FOREIGN KEY (VARIANTSOGLASOVANIYA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_SOGLASOVANIE ADD CONSTRAINT RSD_SOGLASOVANIE_FK_VARIANTUSTANOVKISROKAOBRABOTKIREZULTATOV_ID FOREIGN KEY (VARIANTUSTANOVKISROKAOBRABOTKIREZULTATOV_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_SOGLASOVANIE ADD CONSTRAINT RSD_SOGLASOVANIE_FK_REZULTATSOGLASOVANIYA_ID FOREIGN KEY (REZULTATSOGLASOVANIYA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_SOGLASOVANIE ADD CONSTRAINT RSD_SOGLASOVANIE_FK_SOSTOYANIE_ID FOREIGN KEY (SOSTOYANIE_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY ADD CONSTRAINT RSD_SOGLASOVANIE_DOPOLNITELNYEREKVIZITY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_SOGLASOVANIE (ID);
ALTER TABLE RSD_SOGLASOVANIE_ISPOLNITELI ADD CONSTRAINT RSD_SOGLASOVANIE_ISPOLNITELI_FK_VARIANTUSTANOVKISROKAISPOLNENIYA_ID FOREIGN KEY (VARIANTUSTANOVKISROKAISPOLNENIYA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_SOGLASOVANIE_ISPOLNITELI ADD CONSTRAINT RSD_SOGLASOVANIE_ISPOLNITELI_FK_PORYADOKSOGLASOVANIYA_ID FOREIGN KEY (PORYADOKSOGLASOVANIYA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_SOGLASOVANIE_ISPOLNITELI ADD CONSTRAINT RSD_SOGLASOVANIE_ISPOLNITELI_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_SOGLASOVANIE (ID);
ALTER TABLE RSD_SOGLASOVANIE_PREDMETY ADD CONSTRAINT RSD_SOGLASOVANIE_PREDMETY_FK_ROLPREDMETA_ID FOREIGN KEY (ROLPREDMETA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_SOGLASOVANIE_PREDMETY ADD CONSTRAINT RSD_SOGLASOVANIE_PREDMETY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_SOGLASOVANIE (ID);
ALTER TABLE RSD_SOGLASOVANIE_PREDMETYZADACH ADD CONSTRAINT RSD_SOGLASOVANIE_PREDMETYZADACH_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_SOGLASOVANIE (ID);
ALTER TABLE RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY ADD CONSTRAINT RSD_SOGLASOVANIE_REZULTATYOZNAKOMLENIY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_SOGLASOVANIE (ID);
ALTER TABLE RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA ADD CONSTRAINT RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA_FK_REZULTATSOGLASOVANIYA_ID FOREIGN KEY (REZULTATSOGLASOVANIYA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA ADD CONSTRAINT RSD_SOGLASOVANIE_REZULTATYSOGLASOVANIYA_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_SOGLASOVANIE (ID);
ALTER TABLE RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI ADD CONSTRAINT RSD_SOGLASOVANIE_UDALITDOPOLNITELNYEISPOLNITELI_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_SOGLASOVANIE (ID);
ALTER TABLE RSD_ZADACHAISPOLNITELYA ADD CONSTRAINT RSD_ZADACHAISPOLNITELYA_FK_AVTOR_ID FOREIGN KEY (AVTOR_ID) REFERENCES RSD_POLZOVATELI (ID);
ALTER TABLE RSD_ZADACHAISPOLNITELYA ADD CONSTRAINT RSD_ZADACHAISPOLNITELYA_FK_VAZHNOST_ID FOREIGN KEY (VAZHNOST_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_ZADACHAISPOLNITELYA ADD CONSTRAINT RSD_ZADACHAISPOLNITELYA_FK_SOSTOYANIEBIZNESPROTSESSA_ID FOREIGN KEY (SOSTOYANIEBIZNESPROTSESSA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY ADD CONSTRAINT RSD_ZADACHAISPOLNITELYA_DOPOLNITELNYEREKVIZITY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_ZADACHAISPOLNITELYA (ID);
ALTER TABLE RSD_ZADACHAISPOLNITELYA_PREDMETY ADD CONSTRAINT RSD_ZADACHAISPOLNITELYA_PREDMETY_FK_ROLPREDMETA_ID FOREIGN KEY (ROLPREDMETA_ID) REFERENCES RSD_ENUMS (ID);
ALTER TABLE RSD_ZADACHAISPOLNITELYA_PREDMETY ADD CONSTRAINT RSD_ZADACHAISPOLNITELYA_PREDMETY_FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES RSD_ZADACHAISPOLNITELYA (ID);
